// apps/app/components/token-swap.tsx
"use client"

import { useEffect, useState } from "react"
import { ArrowDownIcon } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"

import { createFrontendSdk } from "@repo/contracts"

const tokens = [
    { value: "eth", label: "Ethereum (ETH)" },
    { value: "usdt", label: "Tether (USDT)" },
]

const sdk = createFrontendSdk()

function getExchangeRate(
    fromToken: string,
    toToken: string,

) {
    if (fromToken === "eth") {
        return 2545
    } else {
        return 0.000382
    }
}

export default function TokenSwap() {
    const [fromAmount, setFromAmount] = useState("")
    const [toAmount, setToAmount] = useState("")
    const [fromToken, setFromToken] = useState("")
    const [toToken, setToToken] = useState("")
    const [error, setError] = useState("")
    const [exchangeRate, setExchangeRate] = useState(4)

    useEffect(() => {
        setToAmount(String(Number(fromAmount) * exchangeRate))
    }, [exchangeRate, fromAmount])

    useEffect(() => {
        setExchangeRate(getExchangeRate(fromToken, toToken))
    }, [fromToken, toToken])

    const handleSwap = () => {
        if (!fromAmount || !toAmount || !fromToken || !toToken) {
            setError("Please fill in all fields")
            return
        }
        if (fromToken === toToken) {
            setError("Cannot swap the same token")
            return
        }
        setError("")
        console.log(`Swapping ${fromAmount} ${fromToken} to ${toAmount} ${toToken}`)
        // Here you would typically call your swap function or API
    }

    return (
        <Card className="w-full max-w-md mx-auto">
            <CardHeader>
                <CardTitle>Crypto Token Swap</CardTitle>
                <CardDescription>Exchange your tokens instantly</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
                <div className="space-y-2">
                    <div className="flex space-x-2">
                        <Input
                            type="number"
                            placeholder="0.00"
                            value={fromAmount}
                            onChange={(e) => setFromAmount(e.target.value)}
                            className="flex-grow"
                        />
                        <Select value={fromToken} onValueChange={setFromToken}>
                            <SelectTrigger className="w-[180px]">
                                <SelectValue placeholder="Select token" />
                            </SelectTrigger>
                            <SelectContent>
                                {tokens.map((token) => (
                                    <SelectItem key={token.value} value={token.value}>
                                        {token.label}
                                    </SelectItem>
                                ))}
                            </SelectContent>
                        </Select>
                    </div>
                </div>
                <div className="flex justify-center">
                    <ArrowDownIcon className="text-gray-500" />
                </div>
                <div className="space-y-2">
                    <div className="flex space-x-2">
                        <Input
                            type="number"
                            placeholder="0.00"
                            value={toAmount}
                            onChange={(e) => setToAmount(e.target.value)}
                            className="flex-grow"
                        />
                        <Select value={toToken} onValueChange={setToToken}>
                            <SelectTrigger className="w-[180px]">
                                <SelectValue placeholder="Select token" />
                            </SelectTrigger>
                            <SelectContent>
                                {tokens.map((token) => (
                                    <SelectItem key={token.value} value={token.value}>
                                        {token.label}
                                    </SelectItem>
                                ))}
                            </SelectContent>
                        </Select>
                    </div>
                </div>
                {error && <p className="text-red-500 text-sm">{error}</p>}
            </CardContent>
            <CardFooter>
                <Button className="w-full" onClick={handleSwap}>
                    Swap Tokens
                </Button>
            </CardFooter>
        </Card>
    )
}

// apps/app-svelte/src/lib/components/TokenSwap.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { ArrowDown } from "lucide-svelte";
  import { Button } from "$lib/components/ui/button";
  import {
    Card,
    CardContent,
    CardDescription,
    CardFooter,
    CardHeader,
    CardTitle,
  } from "$lib/components/ui/card";
  import { Input } from "$lib/components/ui/input";
  import * as Select from "$lib/components/ui/select";

  // Import the SDK (you may need to adjust the import path)
  import {
    createFrontendSdk,
    parseCurrencyAmount,
    formatCurrencyAmount,
  } from "@repo/contracts";

  const sdk = createFrontendSdk();

  const tokens = sdk.currencyList.getCurrencies().map((token) => ({
    value: token.symbol,
    label: token.symbol,
  }));

  let fromAmount = "";
  let toAmount = "";
  let fromToken = "";
  let toToken = "";
  let error = "";
  let exchangeRate = 0;
  let quote = undefined;

  async function getExchangeRate(
    fromToken: string,
    toToken: string,
    fromAmount: string,
  ) {
    try {
      console.log(fromToken, toToken, fromAmount);
      quote = await sdk.prols.getQuote({
        amountIn: parseCurrencyAmount(
          sdk.currencyList.getBySymbol(fromToken)!,
          fromAmount,
        ),
        currencyOut: sdk.currencyList.getBySymbol(toToken)!,
      });
    } catch (e) {
      //   console.error(e);
    }
  }

  $: {
    toAmount = String(Number(fromAmount) * exchangeRate);
  }

  $: {
    getExchangeRate(fromToken, toToken, fromAmount);
  }

  async function handleSwap() {
    const account = await sdk.prols.connectWallet();

    if (!fromAmount || !toAmount || !fromToken || !toToken) {
      error = "Please fill in all fields";
      return;
    }
    if (fromToken === toToken) {
      error = "Cannot swap the same token";
      return;
    }
    error = "";
    console.log(
      `Swapping ${fromAmount} ${fromToken} to ${toAmount} ${toToken}`,
    );
    // Here you would typically call your swap function or API
    // sdk.prols.swap({ account: account, quote:
  }
</script>

<Card class="w-full max-w-md mx-auto">
  <CardHeader>
    <CardTitle>Crypto Token Swap</CardTitle>
    <CardDescription>Exchange your tokens instantly</CardDescription>
  </CardHeader>
  <CardContent class="space-y-4">
    <div class="space-y-2">
      <div class="flex space-x-2">
        <Input
          type="number"
          placeholder="0.00"
          bind:value={fromAmount}
          class="flex-grow"
        />

        <Select.Root
          onSelectedChange={(e) => {
            // @ts-ignore
            fromToken = e.value;
          }}
          portal={null}
        >
          <Select.Trigger class="w-[180px]">
            <Select.Value placeholder="Select token" />
          </Select.Trigger>
          <Select.Content>
            <Select.Group>
              <Select.Label>Tokens</Select.Label>
              {#each tokens as token}
                <Select.Item value={token.value} label={token.label}>
                  {token.label}
                </Select.Item>
              {/each}
            </Select.Group>
          </Select.Content>
          <Select.Input name="fromToken" />
        </Select.Root>
      </div>
    </div>
    <div class="flex justify-center">
      <ArrowDown class="text-gray-500" />
    </div>
    <div class="space-y-2">
      <div class="flex space-x-2">
        <Input
          type="number"
          placeholder="0.00"
          value={quote ? formatCurrencyAmount(quote?.amountOut) : "0"}
          class="flex-grow"
        />
        <Select.Root
          onSelectedChange={(e) => {
            // @ts-ignore
            toToken = e.value;
          }}
          portal={null}
        >
          <Select.Trigger class="w-[180px]">
            <Select.Value placeholder="Select token" />
          </Select.Trigger>
          <Select.Content>
            <Select.Group>
              <Select.Label>Tokens</Select.Label>
              {#each tokens as token}
                <Select.Item value={token.value} label={token.label}>
                  {token.label}
                </Select.Item>
              {/each}
            </Select.Group>
          </Select.Content>
          <Select.Input name="fromToken" />
        </Select.Root>
      </div>
    </div>
    {#if error}
      <p class="text-red-500 text-sm">{error}</p>
    {/if}
  </CardContent>
  <CardFooter>
    <Button class="w-full" on:click={handleSwap}>Swap Tokens</Button>
  </CardFooter>
</Card>
